api_platform:
    title: Veglab API
    version: 1.0.0
    show_webby: false
    
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
