vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'vichUploaderDirectoryName', transliterate: false }
